<<<<<<< HEAD
=======
#-------------------------------------------------------------------------------
# Copyright (c) 2013 TerraFrame, Inc. All rights reserved. 
# 
# This file is part of Runway SDK(tm).
# 
# Runway SDK(tm) is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# Runway SDK(tm) is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with Runway SDK(tm).  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
>>>>>>> ac74a14d84b3e01d5aba7001dc0bc6e12cfc0860
-------------------------------------------------------------------------------
Test set: com.runwaysdk.SessionTestSuite_MavenTest
-------------------------------------------------------------------------------
Tests run: 29, Failures: 0, Errors: 12, Skipped: 0, Time elapsed: 26.887 sec <<< FAILURE!
junit.framework.TestSuite@1a588b85  Time elapsed: 49.067 sec  <<< ERROR!
com.runwaysdk.dataaccess.DuplicateDataException: A user already exists with the username [smethie]
	at com.runwaysdk.business.rbac.UserDAO.apply_aroundBody0(UserDAO.java:71)
	at com.runwaysdk.business.rbac.UserDAO.apply(UserDAO.java:1)
	at com.runwaysdk.session.SessionTest.classSetUp_aroundBody0(SessionTest.java:201)
	at com.runwaysdk.session.SessionTest.classSetUp_aroundBody1$advice(SessionTest.java:854)
	at com.runwaysdk.session.SessionTest.classSetUp(SessionTest.java:1)
	at com.runwaysdk.session.SessionTest$1.setUp(SessionTest.java:177)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:18)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.extensions.TestSetup.run(TestSetup.java:23)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:98)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

junit.framework.TestSuite@4c2f82c0  Time elapsed: 49.071 sec  <<< ERROR!
com.runwaysdk.dataaccess.DuplicateDataException: A user already exists with the username [smethie]
	at com.runwaysdk.business.rbac.UserDAO.apply_aroundBody0(UserDAO.java:71)
	at com.runwaysdk.business.rbac.UserDAO.apply(UserDAO.java:1)
	at com.runwaysdk.session.IntegratedSessionTest.classSetUp_aroundBody0(IntegratedSessionTest.java:297)
	at com.runwaysdk.session.IntegratedSessionTest.classSetUp_aroundBody1$advice(IntegratedSessionTest.java:854)
	at com.runwaysdk.session.IntegratedSessionTest.classSetUp(IntegratedSessionTest.java:1)
	at com.runwaysdk.session.IntegratedSessionTest$1.setUp(IntegratedSessionTest.java:275)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:18)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.extensions.TestSetup.run(TestSetup.java:23)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:98)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

junit.framework.TestSuite@19824dba  Time elapsed: 49.081 sec  <<< ERROR!
com.runwaysdk.dataaccess.DuplicateDataException: A user already exists with the username [smethie]
	at com.runwaysdk.business.rbac.UserDAO.apply_aroundBody0(UserDAO.java:71)
	at com.runwaysdk.business.rbac.UserDAO.apply(UserDAO.java:1)
	at com.runwaysdk.session.SessionTest.classSetUp_aroundBody0(SessionTest.java:201)
	at com.runwaysdk.session.SessionTest.classSetUp(SessionTest.java:1)
	at com.runwaysdk.session.FileSessionTest.classSetUp_aroundBody0(FileSessionTest.java:63)
	at com.runwaysdk.session.FileSessionTest.classSetUp_aroundBody1$advice(FileSessionTest.java:854)
	at com.runwaysdk.session.FileSessionTest.classSetUp(FileSessionTest.java:1)
	at com.runwaysdk.session.FileSessionTest$1.setUp(FileSessionTest.java:36)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:18)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.extensions.TestSetup.run(TestSetup.java:23)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:98)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

junit.framework.TestSuite@74695af5  Time elapsed: 49.091 sec  <<< ERROR!
com.runwaysdk.dataaccess.DuplicateDataException: A user already exists with the username [smethie]
	at com.runwaysdk.business.rbac.UserDAO.apply_aroundBody0(UserDAO.java:71)
	at com.runwaysdk.business.rbac.UserDAO.apply(UserDAO.java:1)
	at com.runwaysdk.session.IntegratedSessionTest.classSetUp_aroundBody0(IntegratedSessionTest.java:297)
	at com.runwaysdk.session.IntegratedSessionTest.classSetUp(IntegratedSessionTest.java:1)
	at com.runwaysdk.session.IntegratedFileSessionTest.classSetUp_aroundBody0(IntegratedFileSessionTest.java:65)
	at com.runwaysdk.session.IntegratedFileSessionTest.classSetUp_aroundBody1$advice(IntegratedFileSessionTest.java:854)
	at com.runwaysdk.session.IntegratedFileSessionTest.classSetUp(IntegratedFileSessionTest.java:1)
	at com.runwaysdk.session.IntegratedFileSessionTest$1.setUp(IntegratedFileSessionTest.java:38)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:18)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.extensions.TestSetup.run(TestSetup.java:23)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:98)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

junit.framework.TestSuite@4cf9b7fa  Time elapsed: 49.099 sec  <<< ERROR!
com.runwaysdk.dataaccess.DuplicateDataException: A user already exists with the username [smethie]
	at com.runwaysdk.business.rbac.UserDAO.apply_aroundBody0(UserDAO.java:71)
	at com.runwaysdk.business.rbac.UserDAO.apply(UserDAO.java:1)
	at com.runwaysdk.session.SessionTest.classSetUp_aroundBody0(SessionTest.java:201)
	at com.runwaysdk.session.SessionTest.classSetUp(SessionTest.java:1)
	at com.runwaysdk.session.BufferedSessionTest.classSetUp_aroundBody0(BufferedSessionTest.java:57)
	at com.runwaysdk.session.BufferedSessionTest.classSetUp_aroundBody1$advice(BufferedSessionTest.java:854)
	at com.runwaysdk.session.BufferedSessionTest.classSetUp(BufferedSessionTest.java:1)
	at com.runwaysdk.session.BufferedSessionTest$1.setUp(BufferedSessionTest.java:30)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:18)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.extensions.TestSetup.run(TestSetup.java:23)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:98)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

junit.framework.TestSuite@4c909176  Time elapsed: 49.113 sec  <<< ERROR!
com.runwaysdk.dataaccess.DuplicateDataException: A user already exists with the username [smethie]
	at com.runwaysdk.business.rbac.UserDAO.apply_aroundBody0(UserDAO.java:71)
	at com.runwaysdk.business.rbac.UserDAO.apply(UserDAO.java:1)
	at com.runwaysdk.session.IntegratedSessionTest.classSetUp_aroundBody0(IntegratedSessionTest.java:297)
	at com.runwaysdk.session.IntegratedSessionTest.classSetUp(IntegratedSessionTest.java:1)
	at com.runwaysdk.session.IntegratedBufferedSessionTest.classSetUp_aroundBody0(IntegratedBufferedSessionTest.java:65)
	at com.runwaysdk.session.IntegratedBufferedSessionTest.classSetUp_aroundBody1$advice(IntegratedBufferedSessionTest.java:854)
	at com.runwaysdk.session.IntegratedBufferedSessionTest.classSetUp(IntegratedBufferedSessionTest.java:1)
	at com.runwaysdk.session.IntegratedBufferedSessionTest$1.setUp(IntegratedBufferedSessionTest.java:38)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:18)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.extensions.TestSetup.run(TestSetup.java:23)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:98)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

junit.framework.TestSuite@51651e77  Time elapsed: 49.127 sec  <<< ERROR!
com.runwaysdk.dataaccess.DuplicateDataException: A user already exists with the username [smethie]
	at com.runwaysdk.business.rbac.UserDAO.apply_aroundBody0(UserDAO.java:71)
	at com.runwaysdk.business.rbac.UserDAO.apply(UserDAO.java:1)
	at com.runwaysdk.session.SessionTest.classSetUp_aroundBody0(SessionTest.java:201)
	at com.runwaysdk.session.SessionTest.classSetUp(SessionTest.java:1)
	at com.runwaysdk.session.OverflowSessionTest.classSetUp_aroundBody0(OverflowSessionTest.java:65)
	at com.runwaysdk.session.OverflowSessionTest.classSetUp_aroundBody1$advice(OverflowSessionTest.java:854)
	at com.runwaysdk.session.OverflowSessionTest.classSetUp(OverflowSessionTest.java:1)
	at com.runwaysdk.session.OverflowSessionTest$1.setUp(OverflowSessionTest.java:38)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:18)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.extensions.TestSetup.run(TestSetup.java:23)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:98)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

junit.framework.TestSuite@7a012d08  Time elapsed: 49.146 sec  <<< ERROR!
com.runwaysdk.dataaccess.DuplicateDataException: A user already exists with the username [smethie]
	at com.runwaysdk.business.rbac.UserDAO.apply_aroundBody0(UserDAO.java:71)
	at com.runwaysdk.business.rbac.UserDAO.apply(UserDAO.java:1)
	at com.runwaysdk.session.IntegratedSessionTest.classSetUp_aroundBody0(IntegratedSessionTest.java:297)
	at com.runwaysdk.session.IntegratedSessionTest.classSetUp(IntegratedSessionTest.java:1)
	at com.runwaysdk.session.IntegratedOverflowTest.classSetUp_aroundBody0(IntegratedOverflowTest.java:71)
	at com.runwaysdk.session.IntegratedOverflowTest.classSetUp_aroundBody1$advice(IntegratedOverflowTest.java:854)
	at com.runwaysdk.session.IntegratedOverflowTest.classSetUp(IntegratedOverflowTest.java:1)
	at com.runwaysdk.session.IntegratedOverflowTest$1.setUp(IntegratedOverflowTest.java:38)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:18)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.extensions.TestSetup.run(TestSetup.java:23)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:98)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

junit.framework.TestSuite@5f18e033  Time elapsed: 49.157 sec  <<< ERROR!
com.runwaysdk.dataaccess.DuplicateDataException: A user already exists with the username [smethie]
	at com.runwaysdk.business.rbac.UserDAO.apply_aroundBody0(UserDAO.java:71)
	at com.runwaysdk.business.rbac.UserDAO.apply(UserDAO.java:1)
	at com.runwaysdk.session.SessionTest.classSetUp_aroundBody0(SessionTest.java:201)
	at com.runwaysdk.session.SessionTest.classSetUp(SessionTest.java:1)
	at com.runwaysdk.session.MemorySessionTest.classSetUp_aroundBody0(MemorySessionTest.java:57)
	at com.runwaysdk.session.MemorySessionTest.classSetUp_aroundBody1$advice(MemorySessionTest.java:854)
	at com.runwaysdk.session.MemorySessionTest.classSetUp(MemorySessionTest.java:1)
	at com.runwaysdk.session.MemorySessionTest$1.setUp(MemorySessionTest.java:30)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:18)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.extensions.TestSetup.run(TestSetup.java:23)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:98)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

junit.framework.TestSuite@57e78575  Time elapsed: 49.167 sec  <<< ERROR!
com.runwaysdk.dataaccess.DuplicateDataException: A user already exists with the username [smethie]
	at com.runwaysdk.business.rbac.UserDAO.apply_aroundBody0(UserDAO.java:71)
	at com.runwaysdk.business.rbac.UserDAO.apply(UserDAO.java:1)
	at com.runwaysdk.session.IntegratedSessionTest.classSetUp_aroundBody0(IntegratedSessionTest.java:297)
	at com.runwaysdk.session.IntegratedSessionTest.classSetUp(IntegratedSessionTest.java:1)
	at com.runwaysdk.session.IntegratedMemorySessionTest.classSetUp_aroundBody0(IntegratedMemorySessionTest.java:57)
	at com.runwaysdk.session.IntegratedMemorySessionTest.classSetUp_aroundBody1$advice(IntegratedMemorySessionTest.java:854)
	at com.runwaysdk.session.IntegratedMemorySessionTest.classSetUp(IntegratedMemorySessionTest.java:1)
	at com.runwaysdk.session.IntegratedMemorySessionTest$1.setUp(IntegratedMemorySessionTest.java:30)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:18)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.extensions.TestSetup.run(TestSetup.java:23)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:98)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

junit.framework.TestSuite@1af76e7a  Time elapsed: 19.112 sec  <<< ERROR!
com.runwaysdk.business.generation.CompilerException: Errors found during compilation:
----------
1. ERROR in /usr/share/tomcat6/.hudson/jobs/Test Runway/workspace/runwaysdk-test/src/main/java-gen/server/stub/test/generated/Collection.java (at line 177)
	com.runwaysdk.query.ValueQueryExcelExporter excelExporter = new com.runwaysdk.query.ValueQueryExcelExporter(valueQuery, "Test Sheet");
	                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The constructor ValueQueryExcelExporter(ValueQuery, String) is undefined
----------
2. ERROR in /usr/share/tomcat6/.hudson/jobs/Test Runway/workspace/runwaysdk-test/src/main/java-gen/server/stub/test/generated/Collection.java (at line 190)
	com.runwaysdk.query.ValueQueryExcelExporter excelExporter = new com.runwaysdk.query.ValueQueryExcelExporter(valueQuery, "Test Sheet");
	                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The constructor ValueQueryExcelExporter(ValueQuery, String) is undefined
----------
2 problems (2 errors)
	at com.runwaysdk.business.generation.EclipseCompiler.callECJ(EclipseCompiler.java:63)
	at com.runwaysdk.business.generation.EclipseCompiler.execute(EclipseCompiler.java:36)
	at com.runwaysdk.business.generation.AbstractCompiler.compileAll(AbstractCompiler.java:185)
	at com.runwaysdk.business.generation.AbstractCompiler.compileAllNoOutput(AbstractCompiler.java:168)
	at com.runwaysdk.business.generation.GenerationFacade.compileAllNoOutput(GenerationFacade.java:256)
	at com.runwaysdk.dataaccess.transaction.TransactionManagement.generateAndCompileClasses(TransactionManagement.aj:368)
	at com.runwaysdk.dataaccess.transaction.TransactionManagement.processTransaction(TransactionManagement.aj:101)
	at com.runwaysdk.dataaccess.transaction.AbstractTransactionManagement.ajc$inlineAccessMethod$com_runwaysdk_dataaccess_transaction_AbstractTransactionManagement$com_runwaysdk_dataaccess_transaction_AbstractTransactionManagement$processTransaction(AbstractTransactionManagement.aj:1)
	at com.runwaysdk.session.MethodTest.classTearDown_aroundBody3$advice(MethodTest.java:871)
	at com.runwaysdk.session.MethodTest.classTearDown(MethodTest.java:1)
	at com.runwaysdk.session.MethodTest$1.tearDown(MethodTest.java:127)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:20)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.extensions.TestSetup.run(TestSetup.java:23)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:98)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

junit.framework.TestSuite@52661a85  Time elapsed: 19.116 sec  <<< ERROR!
com.runwaysdk.dataaccess.DuplicateDataException: A user already exists with the username [smethie]
	at com.runwaysdk.business.rbac.UserDAO.apply_aroundBody0(UserDAO.java:71)
	at com.runwaysdk.business.rbac.UserDAO.apply(UserDAO.java:1)
	at com.runwaysdk.session.IntegratedMethodTest.classSetUp_aroundBody0(IntegratedMethodTest.java:336)
	at com.runwaysdk.session.IntegratedMethodTest.classSetUp_aroundBody1$advice(IntegratedMethodTest.java:854)
	at com.runwaysdk.session.IntegratedMethodTest.classSetUp(IntegratedMethodTest.java:1)
	at com.runwaysdk.session.IntegratedMethodTest$1.setUp(IntegratedMethodTest.java:312)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:18)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.extensions.TestSetup.run(TestSetup.java:23)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:98)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)

